---
# ansible playbook for installing nginx

- name: import nginx repo key
  rpm_key: >
    key=http://nginx.org/keys/nginx_signing.key
    state=present

- name: install nginx repo
  yum: >
    name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
    state=present

- name: install nginx
  yum: name=nginx state=present

- name: nginx main config file
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644
  notify: reload nginx

- name: nginx http config file
  template: >
    src=nginx.default.conf.j2
    dest=/etc/nginx/conf.d/default.conf
    owner=root
    group=root
    mode=0644
  notify: reload nginx

- name: nginx http location config file directory
  file: >
    path=/etc/nginx/conf.d/location.d
    state=directory
    owner=root
    group=root
    mode=0755

- name: nginx https config file
  template: >
    src=ssl.conf.j2
    dest=/etc/nginx/conf.d/ssl.conf
    owner=root
    group=root
    mode=0644
  notify: reload nginx

- name: nginx https location config file directory
  file: >
    path=/etc/nginx/conf.d/ssl.location.d
    state=directory
    owner=root
    group=root
    mode=0755

- name: start nginx service
  service: name=nginx state=started enabled=yes
