---

- name: install monit
  yum: name=monit

- name: monit main config
  template: >
    src=monit.conf.j2
    dest=/etc/monit.conf
    owner=root
    group=root
    mode=0600
  notify: reload monit

- name: monit additional config files
  template: >
    src={{ item }}.conf.j2
    dest=/etc/monit.d/{{ item }}.conf
    owner=root
    group=root
    mode=0600
  notify: reload monit
  with_items:
    - monit_http
    - send_alert_mails
    - system
    - root_filesystem
    - sshd
    - ntpd
    - crond
    - nginx
    - spawn-fcgi
    - php-fpm
    - gmond
    - gmetad
    - jenkins

- name: start monit service
  service: name=monit state=started enabled=yes
