---
- hosts: all
  user: vagrant

  vars:
    - rbenv_root: /usr/local/rbenv
    - ruby_version: 2.0.0-p247

  tasks:
    - name: rubyのビルドに必要なパッケージをインストール
      sudo: yes
      yum: name=$item state=latest
      with_items:
        - make
        - gcc
        - zlib-devel
        - openssl-devel
        - readline-devel
        - ncurses-devel
        - git

    - name: rbenvをリポジトリから取得
      sudo: yes
      git: repo=git://github.com/sstephenson/rbenv.git dest=$rbenv_root

    - name: ruby-buildをリポジトリから取得
      sudo: yes
      git: repo=git://github.com/sstephenson/ruby-build.git dest=$rbenv_root/plugins/ruby-build

    - name: /etc/profile.d 以下に rbenv.shを配置
      sudo: yes
      template: src=rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh

    - name: rbenv.shを読み込み
      sudo: yes
      shell: source /etc/profile.d/rbenv.sh

    - name: ruby $ruby_version をインストール
      sudo: yes
      shell: source /etc/profile.d/rbenv.sh; rbenv install $ruby_version

    - name: ruby $ruby_version をglobalにセット
      sudo: yes
      shell: source /etc/profile.d/rbenv.sh; rbenv global $ruby_version

    - name: rbenv rehashの実行
      sudo: yes
      shell: source /etc/profile.d/rbenv.sh; rbenv rehash

    - name: bundlerのインストール
      sudo: yes
      shell: source /etc/profile.d/rbenv.sh; gem install bundler --no-ri --no-rdoc

    - name: bluepillのインストール
      sudo: yes
      shell: source /etc/profile.d/rbenv.sh; gem install bluepill --no-ri --no-rdoc

    - name: rbenv rehashの実行
      sudo: yes
      shell: source /etc/profile.d/rbenv.sh; rbenv rehash
