---

- name: get rbenv $rbenv_repo
  sudo: yes
  git: >
    repo=$rbenv_repo
    dest=$rbenv_root

- name: get ruby-build $ruby_build_repo
  sudo: yes
  git: >
    repo=$ruby_build_repo
    dest=$rbenv_root/plugins/ruby-build

- name: setting rbenv.sh to /etc/profile.d
  sudo: yes
  template: >
    src=rbenv.sh.j2
    dest=/etc/profile.d/rbenv.sh
